apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: mattermost
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: mattermost
  POSTGRES_PASSWORD: chocolateFrog!