configJSON: {
  "ServiceSettings": {
    "SiteURL": "http://controller.team1-ccs-hw6-mm.jhucloudsec2025.emulab.net"
  }
}
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - mattermost.192.168.100.241.nip.io
  tls: []
