configJSON: {
  "ServiceSettings": {
    "SiteURL": "http://mattermost.10.0.0.234.nip.io:31651"
  }
}
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - mattermost.10.0.0.234.nip.io
  tls: []
